outpath: './santas'
asciiartpath: 'ascii_tree.txt'

candidates:
    # Candidate name: [List of people that may not recieve a gift from candidate]
    Alice: [Bob]
    Bob: [Alice]
    Charlene:
    David:
